package com.nasiat_muhib.classmate.strings

const val CLASS_DEPARTMENT = "class_department"
const val CLASS_COURSE_CODE = "class_course_code"
const val CLASS_COURSE_CREATOR = "class_course_creator"
const val CLASS_NO = "class_no"
const val WEEKDAY = "week_day"
const val CLASSROOM = "classroom"
const val SECTION = "section"
const val START_HOUR = "start_hour"
const val START_MINUTE = "start_minute"
const val START_SHIFT = "start_shift"
const val END_HOUR = "end_hour"
const val END_MINUTE = "end_minute"
const val END_SHIFT = "end_shift"
const val ACTIVE_STATUS = "active_status"

// WeekDays
const val SUNDAY = "Sun"
const val MONDAY = "Mon"
const val TUESDAY = "Tue"
const val WEDNESDAY = "Wed"
const val THURSDAY = "Thu"
const val FRIDAY = "Fri"
const val SATURDAY = "Sat"